# Generated by Django 3.0.6 on 2020-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
